apiVersion: v1
kind: Service
metadata:
  name: operator
  namespace: offline-search
spec:
  type: NodePort
  selector:
    app: operator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
